from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
import datetime
import io

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total pages and draw headers/footers
    without overlap.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#475569")) # Slate 600

        # Header (Only on pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 755, "LaunchLens AI — GTM Intelligence & Validation Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0")) # Slate 200
            self.setLineWidth(0.5)
            self.line(54, 747, 558, 747)
            
        # Footer (On all pages)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        self.drawString(54, 40, "Confidential — Generated by LaunchLens AI")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 50, 558, 50)
        
        self.restoreState()


def create_gtm_pdf(project) -> bytes:
    """
    Generates a PDF bytes object for the GTM report.
    'project' should be a dictionary containing name, industry, problem, country,
    target_customer, validation_score, opportunity_score, risk_score, data, and created_at.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,  # 0.75 inch
        rightMargin=54,
        topMargin=72,   # 1 inch (provides space for header)
        bottomMargin=72 # 1 inch (provides space for footer)
    )

    data = project.get("data", {})
    styles = getSampleStyleSheet()

    # Define custom styles to avoid conflicts
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0F172A"), # Slate 900
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#475569"), # Slate 600
        spaceAfter=15
    )

    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        textColor=colors.HexColor("#1E3A8A"), # Dark Blue
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        'SubSectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#2563EB"), # Blue 600
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"), # Slate 700
        spaceAfter=8
    )

    bullet_style = ParagraphStyle(
        'ReportBullet',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )

    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#1E293B")
    )

    meta_val_style = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#475569")
    )

    score_num_style = ParagraphStyle(
        'ScoreNum',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        alignment=TA_CENTER
    )

    score_lbl_style = ParagraphStyle(
        'ScoreLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#475569"),
        alignment=TA_CENTER
    )

    story = []

    # -------------------------------------------------------------
    # PAGE 1: TITLE & EXECUTIVE SUMMARY
    # -------------------------------------------------------------
    story.append(Paragraph("LaunchLens AI", title_style))
    story.append(Paragraph("Go-To-Market (GTM) Intelligence & Idea Validation Report", subtitle_style))
    
    # Metadata block
    created_date = project.get("created_at", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    if isinstance(created_date, str) and len(created_date) > 10:
        created_date = created_date[:10]

    meta_data = [
        [Paragraph("Startup Name:", meta_label_style), Paragraph(project.get("name"), meta_val_style),
         Paragraph("Country/Region:", meta_label_style), Paragraph(project.get("country"), meta_val_style)],
        [Paragraph("Industry:", meta_label_style), Paragraph(project.get("industry"), meta_val_style),
         Paragraph("Target Customer:", meta_label_style), Paragraph(project.get("target_customer"), meta_val_style)],
        [Paragraph("Date Generated:", meta_label_style), Paragraph(created_date, meta_val_style),
         Paragraph("Platform:", meta_label_style), Paragraph("LaunchLens AI", meta_val_style)]
    ]

    meta_table = Table(meta_data, colWidths=[90, 162, 100, 152])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")), # Slate 50
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor("#E2E8F0")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 15))

    # Score Cards
    val_score = project.get("validation_score", 0)
    opp_score = project.get("opportunity_score", 0)
    risk_score = project.get("risk_score", 0)

    # Helper function for coloring score text
    def get_score_color(score, is_risk=False):
        if is_risk:
            if score < 40: return colors.HexColor("#16A34A") # Low risk - green
            if score < 70: return colors.HexColor("#D97706") # Med risk - orange
            return colors.HexColor("#DC2626") # High risk - red
        else:
            if score >= 70: return colors.HexColor("#16A34A") # High score - green
            if score >= 50: return colors.HexColor("#D97706") # Med score - orange
            return colors.HexColor("#DC2626") # Low score - red

    val_color = get_score_color(val_score)
    opp_color = get_score_color(opp_score)
    risk_color = get_score_color(risk_score, is_risk=True)

    score_data = [
        [
            Paragraph(f"<font color='{val_color}'>{val_score}/100</font>", score_num_style),
            Paragraph(f"<font color='{opp_color}'>{opp_score}/100</font>", score_num_style),
            Paragraph(f"<font color='{risk_color}'>{risk_score}/100</font>", score_num_style)
        ],
        [
            Paragraph("VALIDATION SCORE", score_lbl_style),
            Paragraph("OPPORTUNITY SCORE", score_lbl_style),
            Paragraph("RISK SCORE", score_lbl_style)
        ]
    ]

    score_table = Table(score_data, colWidths=[168, 168, 168])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F1F5F9")), # Slate 100
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (0, 0), 10),
        ('BOTTOMPADDING', (0, 0), (0, 0), 2),
        ('TOPPADDING', (0, 1), (0, 1), 2),
        ('BOTTOMPADDING', (0, 1), (0, 1), 10),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 15))

    # Executive Summary Text
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(data.get("summary", "No summary available."), body_style))
    story.append(Spacer(1, 10))

    # SWOT Analysis
    story.append(Paragraph("2. SWOT Analysis", h1_style))
    swot = data.get("swot", {})
    
    swot_s = "".join([f"• {item}<br/>" for item in swot.get("strengths", [])])
    swot_w = "".join([f"• {item}<br/>" for item in swot.get("weaknesses", [])])
    swot_o = "".join([f"• {item}<br/>" for item in swot.get("opportunities", [])])
    swot_t = "".join([f"• {item}<br/>" for item in swot.get("threats", [])])

    swot_cell_style = ParagraphStyle('SwotCell', parent=body_style, fontSize=9, leading=12, spaceAfter=0)

    swot_data = [
        [
            Paragraph("<b>STRENGTHS (Internal)</b><br/>" + (swot_s if swot_s else "None identified."), swot_cell_style),
            Paragraph("<b>WEAKNESSES (Internal)</b><br/>" + (swot_w if swot_w else "None identified."), swot_cell_style)
        ],
        [
            Paragraph("<b>OPPORTUNITIES (External)</b><br/>" + (swot_o if swot_o else "None identified."), swot_cell_style),
            Paragraph("<b>THREATS (External)</b><br/>" + (swot_t if swot_t else "None identified."), swot_cell_style)
        ]
    ]

    swot_table = Table(swot_data, colWidths=[252, 252])
    swot_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), colors.HexColor("#F0FDF4")), # Light Green
        ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#FEF2F2")), # Light Red
        ('BACKGROUND', (0, 1), (0, 1), colors.HexColor("#EFF6FF")), # Light Blue
        ('BACKGROUND', (1, 1), (1, 1), colors.HexColor("#FFF7ED")), # Light Orange
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
    ]))
    story.append(swot_table)
    
    # Page Break for clean multi-page transition
    story.append(PageBreak())

    # -------------------------------------------------------------
    # PAGE 2: MARKET RESEARCH & OPPORTUNITY GAP FINDER
    # -------------------------------------------------------------
    story.append(Paragraph("3. Market Research Engine", h1_style))
    story.append(Paragraph("<b>Industry Overview:</b>", h2_style))
    story.append(Paragraph(data.get("industry_overview", "No industry overview available."), body_style))
    
    story.append(Paragraph("<b>Key Market Trends:</b>", h2_style))
    for trend in data.get("market_trends", []):
        story.append(Paragraph(f"• {trend}", bullet_style))
    story.append(Spacer(1, 5))
        
    story.append(Paragraph("<b>Emerging Opportunities:</b>", h2_style))
    for opp in data.get("emerging_opportunities", []):
        story.append(Paragraph(f"• {opp}", bullet_style))
    story.append(Spacer(1, 5))

    story.append(Paragraph("<b>Key Industry Challenges:</b>", h2_style))
    for challenge in data.get("key_challenges", []):
        story.append(Paragraph(f"• {challenge}", bullet_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("4. Market Gap Finder & White Space Analysis", h1_style))
    
    gap_score = data.get("market_gap_opportunity_score", 0)
    gap_color = get_score_color(gap_score)
    story.append(Paragraph(f"<b>Gap Opportunity Score:</b> <font color='{gap_color}'><b>{gap_score}/100</b></font>", body_style))
    
    gap_data = [
        [Paragraph("<b>Underserved Segments:</b>", meta_label_style), Paragraph(data.get("market_gap_underserved_segments", "N/A"), body_style)],
        [Paragraph("<b>Competitor Gaps:</b>", meta_label_style), Paragraph(data.get("market_gap_missing_features", "N/A"), body_style)],
        [Paragraph("<b>Product Opportunities:</b>", meta_label_style), Paragraph(data.get("market_gap_product_opportunities", "N/A"), body_style)]
    ]
    gap_table = Table(gap_data, colWidths=[130, 374])
    gap_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor("#F1F5F9")),
    ]))
    story.append(gap_table)

    story.append(PageBreak())

    # -------------------------------------------------------------
    # PAGE 3: COMPETITOR INTELLIGENCE & TARGET PERSONAS
    # -------------------------------------------------------------
    story.append(Paragraph("5. Competitor Intelligence", h1_style))
    
    comp_header_style = ParagraphStyle('CompHeader', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, leading=11, textColor=colors.HexColor("#FFFFFF"))
    comp_body_style = ParagraphStyle('CompBody', parent=styles['Normal'], fontName='Helvetica', fontSize=8.5, leading=11, textColor=colors.HexColor("#334155"))

    def build_competitor_table(competitors, title):
        comp_rows = [[
            Paragraph("<b>Competitor</b>", comp_header_style),
            Paragraph("<b>Description</b>", comp_header_style),
            Paragraph("<b>Strengths</b>", comp_header_style),
            Paragraph("<b>Weaknesses</b>", comp_header_style),
            Paragraph("<b>Positioning</b>", comp_header_style)
        ]]
        
        for comp in competitors:
            comp_rows.append([
                Paragraph(comp.get("name", "N/A"), ParagraphStyle('CompName', parent=comp_body_style, fontName='Helvetica-Bold')),
                Paragraph(comp.get("description", "N/A"), comp_body_style),
                Paragraph(comp.get("strengths", "N/A"), comp_body_style),
                Paragraph(comp.get("weaknesses", "N/A"), comp_body_style),
                Paragraph(comp.get("positioning", "N/A"), comp_body_style)
            ])
            
        t = Table(comp_rows, colWidths=[90, 110, 104, 100, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        return t

    direct_list = data.get("direct_competitors", [])
    if direct_list:
        story.append(Paragraph("<b>Direct Competitors:</b>", h2_style))
        story.append(build_competitor_table(direct_list, "Direct"))
        story.append(Spacer(1, 10))

    indirect_list = data.get("indirect_competitors", [])
    if indirect_list:
        story.append(Paragraph("<b>Indirect Competitors:</b>", h2_style))
        story.append(build_competitor_table(indirect_list, "Indirect"))
        story.append(Spacer(1, 15))

    story.append(Paragraph("6. Customer Personas", h1_style))
    personas = data.get("personas", [])
    
    persona_cards = []
    for pers in personas:
        persona_content = [
            [Paragraph("<b>Persona Name:</b>", meta_label_style), Paragraph(pers.get("name", "N/A"), body_style)],
            [Paragraph("<b>Target Role:</b>", meta_label_style), Paragraph(pers.get("role", "N/A"), body_style)],
            [Paragraph("<b>User Goals:</b>", meta_label_style), Paragraph(pers.get("goals", "N/A"), body_style)],
            [Paragraph("<b>Pain Points:</b>", meta_label_style), Paragraph(pers.get("pain_points", "N/A"), body_style)],
            [Paragraph("<b>Buying Motivation:</b>", meta_label_style), Paragraph(pers.get("buying_motivation", "N/A"), body_style)]
        ]
        
        pt = Table(persona_content, colWidths=[110, 394])
        pt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor("#EFF6FF")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#DBEAFE")), # Light blue border
        ]))
        
        persona_cards.append(pt)
        persona_cards.append(Spacer(1, 8))
        
    story.extend(persona_cards)
    
    story.append(PageBreak())

    # -------------------------------------------------------------
    # PAGE 4: GTM STRATEGY & INVESTOR READINESS ASSESSMENT
    # -------------------------------------------------------------
    story.append(Paragraph("7. Go-To-Market (GTM) Strategy", h1_style))
    
    gtm = data.get("gtm", {})
    story.append(Paragraph("<b>Ideal Customer Profile (ICP):</b>", h2_style))
    story.append(Paragraph(gtm.get("icp", "N/A"), body_style))
    
    story.append(Paragraph("<b>Product Positioning Statement:</b>", h2_style))
    story.append(Paragraph(gtm.get("positioning", "N/A"), body_style))
    
    story.append(Paragraph("<b>Pricing Strategy:</b>", h2_style))
    story.append(Paragraph(gtm.get("pricing_recommendation", "N/A"), body_style))
    
    story.append(Paragraph("<b>Marketing Channels:</b>", h2_style))
    for channel in gtm.get("marketing_channels", []):
        story.append(Paragraph(f"• {channel}", bullet_style))
    story.append(Spacer(1, 5))
        
    story.append(Paragraph("<b>Sales Strategy:</b>", h2_style))
    story.append(Paragraph(gtm.get("sales_strategy", "N/A"), body_style))
    
    story.append(Paragraph("<b>30-Day Launch Roadmap:</b>", h2_style))
    for step in gtm.get("launch_roadmap_30_day", []):
        story.append(Paragraph(f"• {step}", bullet_style))
    story.append(Spacer(1, 15))

    story.append(Paragraph("8. Investor Readiness Assessment", h1_style))
    
    readiness = data.get("investor_readiness", {})
    
    # Helper to generate inline HTML colored scores
    def inline_score_tag(score):
        c = get_score_color(score)
        return f"<font color='{c}'><b>{score}/100</b></font>"

    readiness_data = [
        [
            Paragraph("<b>Market Attractiveness:</b>", meta_label_style),
            Paragraph(inline_score_tag(readiness.get("market_attractiveness_score", 0)), body_style),
            Paragraph(readiness.get("market_attractiveness_rationale", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Business Viability:</b>", meta_label_style),
            Paragraph(inline_score_tag(readiness.get("business_viability_score", 0)), body_style),
            Paragraph(readiness.get("business_viability_rationale", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Scalability Score:</b>", meta_label_style),
            Paragraph(inline_score_tag(readiness.get("scalability_score", 0)), body_style),
            Paragraph(readiness.get("scalability_rationale", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Funding Readiness:</b>", meta_label_style),
            Paragraph(inline_score_tag(readiness.get("funding_readiness_score", 0)), body_style),
            Paragraph(readiness.get("funding_readiness_rationale", "N/A"), body_style)
        ]
    ]

    readiness_table = Table(readiness_data, colWidths=[130, 60, 314])
    readiness_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor("#F1F5F9")),
    ]))
    
    story.append(readiness_table)

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
